// Compiled shader for PC, Mac & Linux Standalone

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Unlit/Aura" {
Properties {
 _MainTex ("Base (RGB)", 2D) = "white" { }
 _Color ("Color", Color) = (1.000000,1.000000,1.000000,1.000000)
 _Size ("Aura size", Float) = 1.500000
 _Glossiness ("Smoothness", Range(0.000000,1.000000)) = 0.500000
 _Metallic ("Metallic", Range(0.000000,1.000000)) = 0.000000
 _Scale ("Scale", Float) = 1.000000
 _Speed ("Speed", Float) = 1.000000
 _Frequency ("Frequency", Float) = 1.000000
}
SubShader { 
 LOD 200
 Tags { "LIGHTMODE"="FORWARDBASE" "QUEUE"="Transparent" "RenderType"="Opaque" }


 // Stats for Vertex shader:
 //         d3d9: 41 math
 //        d3d11: 35 math
 // Stats for Fragment shader:
 //         d3d9: 4 math, 1 texture
 //        d3d11: 2 math, 1 texture
 Pass {
  Tags { "LIGHTMODE"="FORWARDBASE" "SHADOWSUPPORT"="true" "RenderType"="Opaque" }
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords set in this variant: DIRECTIONAL 
-- Vertex shader for "d3d9":
// Stats: 41 math
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "TexCoord"

Matrix4x4 unity_MatrixVP at 4
Matrix4x4 unity_ObjectToWorld at 0
Matrix4x3 unity_WorldToObject at 8
Vector4 _LightColor0 at 19
Vector4 _MainTex_ST at 20
Vector4 _WorldSpaceLightPos0 at 11
Vector4 unity_SHAb at 14
Vector4 unity_SHAg at 13
Vector4 unity_SHAr at 12
Vector4 unity_SHBb at 17
Vector4 unity_SHBg at 16
Vector4 unity_SHBr at 15
Vector4 unity_SHC at 18

Shader Disassembly:
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 _LightColor0;
//   float4 _MainTex_ST;
//   float4 _WorldSpaceLightPos0;
//   row_major float4x4 unity_MatrixVP;
//   row_major float4x4 unity_ObjectToWorld;
//   float4 unity_SHAb;
//   float4 unity_SHAg;
//   float4 unity_SHAr;
//   float4 unity_SHBb;
//   float4 unity_SHBg;
//   float4 unity_SHBr;
//   float4 unity_SHC;
//   row_major float4x4 unity_WorldToObject;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   unity_ObjectToWorld  c0       4
//   unity_MatrixVP       c4       4
//   unity_WorldToObject  c8       3
//   _WorldSpaceLightPos0 c11      1
//   unity_SHAr           c12      1
//   unity_SHAg           c13      1
//   unity_SHAb           c14      1
//   unity_SHBr           c15      1
//   unity_SHBg           c16      1
//   unity_SHBb           c17      1
//   unity_SHC            c18      1
//   _LightColor0         c19      1
//   _MainTex_ST          c20      1
//

    vs_3_0
    def c21, 1.05499995, -0.0549999997, 0, 0
    def c22, 1, 0, 0.416666657, 0
    dcl_position v0
    dcl_normal v1
    dcl_texcoord v2
    dcl_texcoord o0.xy
    dcl_position o1
    dcl_color o2.xyz
    dcl_color1 o3.xyz
    mad r0, v0.xyzx, c22.xxxy, c22.yyyx
    dp4 r1.x, c0, r0
    dp4 r1.y, c1, r0
    dp4 r1.z, c2, r0
    dp4 r1.w, c3, r0
    dp4 r4.x, c4, r1
    dp4 r4.y, c5, r1
    dp4 r4.z, c6, r1
    dp4 r4.w, c7, r1
    mad o0.xy, v2, c20, c20.zwzw
    mul r0.xyz, c9, v1.y
    mad r0.xyz, v1.x, c8, r0
    mad r0.xyz, v1.z, c10, r0
    nrm r1.xyz, r0
    dp3 r0.x, r1, c11
    max r0.x, r0.x, c22.y
    mul o2.xyz, r0.x, c19
    mul r0.x, r1.y, r1.y
    mad r0.x, r1.x, r1.x, -r0.x
    mul r2, r1.yzzx, r1.xyzz
    dp4 r3.x, c15, r2
    dp4 r3.y, c16, r2
    dp4 r3.z, c17, r2
    mad r0.xyz, c18, r0.x, r3
    mov r1.w, c22.x
    dp4 r2.x, c12, r1
    dp4 r2.y, c13, r1
    dp4 r2.z, c14, r1
    add r0.xyz, r0, r2
    max r0.xyz, r0, c22.y
    log r1.x, r0.x
    log r1.y, r0.y
    log r1.z, r0.z
    mul r0.xyz, r1, c22.z
    exp r1.x, r0.x
    exp r1.y, r0.y
    exp r1.z, r0.z
    mad r0.xyz, r1, c21.x, c21.y
    max o3.xyz, r0, c22.y
    mad o1.xy, r4.w, c255, r4
    mov o1.zw, r4

// approximately 43 instruction slots used


-- Fragment shader for "d3d9":
// Stats: 4 math, 1 textures
Set 2D Texture "_MainTex" to slot 0

Shader Disassembly:
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   sampler2D _MainTex;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   _MainTex     s0       1
//

    ps_3_0
    dcl_texcoord v0.xy
    dcl_color v1.xyz
    dcl_color1 v2.xyz
    dcl_2d s0
    mov r0.xyz, v1
    add_pp r0.xyz, r0, v2
    texld_pp r1, v0, s0
    mul_pp oC0.xyz, r0, r1
    mov_pp oC0.w, r1.w

// approximately 5 instruction slots used (1 texture, 4 arithmetic)


-- Vertex shader for "d3d11":
// Stats: 35 math, 4 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "TexCoord"

Constant Buffer "$Globals" (80 bytes) on slot 0 {
  Vector4 _LightColor0 at 32
  Vector4 _MainTex_ST at 64
}
Constant Buffer "UnityLighting" (752 bytes) on slot 1 {
  Vector4 _WorldSpaceLightPos0 at 0
  Vector4 unity_SHAr at 608
  Vector4 unity_SHAg at 624
  Vector4 unity_SHAb at 640
  Vector4 unity_SHBr at 656
  Vector4 unity_SHBg at 672
  Vector4 unity_SHBb at 688
  Vector4 unity_SHC at 704
}
Constant Buffer "UnityPerDraw" (160 bytes) on slot 2 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 3 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz 
// NORMAL                   0   xyzw        1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// SV_POSITION              0   xyzw        1      POS   float   xyzw
// COLOR                    0   xyz         2     NONE   float   xyz 
// COLOR                    1   xyz         3     NONE   float   xyz 
//
      vs_4_0
      dcl_constantbuffer CB0[5], immediateIndexed
      dcl_constantbuffer CB1[45], immediateIndexed
      dcl_constantbuffer CB2[7], immediateIndexed
      dcl_constantbuffer CB3[21], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_input v2.xy
      dcl_output o0.xy
      dcl_output_siv o1.xyzw, position
      dcl_output o2.xyz
      dcl_output o3.xyz
      dcl_temps 4
   0: mad o0.xy, v2.xyxx, cb0[4].xyxx, cb0[4].zwzz
   1: mul r0.xyzw, v0.yyyy, cb2[1].xyzw
   2: mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
   3: mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
   4: add r0.xyzw, r0.xyzw, cb2[3].xyzw
   5: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
   6: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
   7: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
   8: mad o1.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
   9: dp3 r0.x, v1.xyzx, cb2[4].xyzx
  10: dp3 r0.y, v1.xyzx, cb2[5].xyzx
  11: dp3 r0.z, v1.xyzx, cb2[6].xyzx
  12: dp3 r0.w, r0.xyzx, r0.xyzx
  13: rsq r0.w, r0.w
  14: mul r0.xyz, r0.wwww, r0.xyzx
  15: dp3 r1.x, r0.xyzx, cb1[0].xyzx
  16: max r1.x, r1.x, l(0.000000)
  17: mul o2.xyz, r1.xxxx, cb0[2].xyzx
  18: mul r1.x, r0.y, r0.y
  19: mad r1.x, r0.x, r0.x, -r1.x
  20: mul r2.xyzw, r0.yzzx, r0.xyzz
  21: dp4 r3.x, cb1[41].xyzw, r2.xyzw
  22: dp4 r3.y, cb1[42].xyzw, r2.xyzw
  23: dp4 r3.z, cb1[43].xyzw, r2.xyzw
  24: mad r1.xyz, cb1[44].xyzx, r1.xxxx, r3.xyzx
  25: mov r0.w, l(1.000000)
  26: dp4 r2.x, cb1[38].xyzw, r0.xyzw
  27: dp4 r2.y, cb1[39].xyzw, r0.xyzw
  28: dp4 r2.z, cb1[40].xyzw, r0.xyzw
  29: add r0.xyz, r1.xyzx, r2.xyzx
  30: max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  31: log r0.xyz, r0.xyzx
  32: mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
  33: exp r0.xyz, r0.xyzx
  34: mad r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
  35: max o3.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  36: ret 
// Approximately 0 instruction slots used


-- Fragment shader for "d3d11":
// Stats: 2 math, 2 temp registers, 1 textures
Set 2D Texture "_MainTex" to slot 0

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// SV_POSITION              0   xyzw        1      POS   float       
// COLOR                    0   xyz         2     NONE   float   xyz 
// COLOR                    1   xyz         3     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v0.xy
      dcl_input_ps linear v2.xyz
      dcl_input_ps linear v3.xyz
      dcl_output o0.xyzw
      dcl_temps 2
   0: add r0.xyz, v2.xyzx, v3.xyzx
   1: sample r1.xyzw, v0.xyxx, t0.xyzw, s0
   2: mul o0.xyz, r0.xyzx, r1.xyzx
   3: mov o0.w, r1.w
   4: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords set in this variant: DIRECTIONAL SHADOWS_SCREEN 
-- Vertex shader for "d3d9":
// Compile errors generating this shader.

-- Fragment shader for "d3d9":
// Compile errors generating this shader.

-- Vertex shader for "d3d11":
// Compile errors generating this shader.

-- Fragment shader for "d3d11":
// Compile errors generating this shader.

 }


 // Stats for Vertex shader:
 //         d3d9: 30 math
 //        d3d11: 16 math
 // Stats for Fragment shader:
 //         d3d9: 3 math
 //        d3d11: 1 math
 Pass {
  Tags { "LIGHTMODE"="FORWARDBASE" "QUEUE"="Transparent" "RenderType"="Opaque" }
  ZWrite Off
  Blend SrcAlpha OneMinusSrcAlpha
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
No keywords set in this variant.
-- Vertex shader for "d3d9":
// Stats: 30 math
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "TexCoord"

Matrix4x4 unity_MatrixVP at 4
Matrix4x4 unity_ObjectToWorld at 0
Float _Frequency at 13
Vector4 _MainTex_ST at 10
Float _Scale at 11
Float _Size at 9
Float _Speed at 12
Vector4 _Time at 8

Shader Disassembly:
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float _Frequency;
//   float4 _MainTex_ST;
//   float _Scale;
//   float _Size;
//   float _Speed;
//   float4 _Time;
//   row_major float4x4 unity_MatrixVP;
//   row_major float4x4 unity_ObjectToWorld;
//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   unity_ObjectToWorld c0       4
//   unity_MatrixVP      c4       4
//   _Time               c8       1
//   _Size               c9       1
//   _MainTex_ST         c10      1
//   _Scale              c11      1
//   _Speed              c12      1
//   _Frequency          c13      1
//

    vs_3_0
    def c14, 0.159154937, 0.5, 6.28318548, -3.14159274
    def c15, 1, 0, 0, 0
    dcl_position v0
    dcl_normal v1
    dcl_texcoord v2
    dcl_texcoord o0.xy
    dcl_position o1
    dcl_normal o2.xyz
    add r0.x, v0.z, v0.x
    mov r0.w, c8.w
    mul r0.y, r0.w, c12.x
    mad r0.x, r0.y, c13.x, r0.x
    mad r0.x, r0.x, c14.x, c14.y
    frc r0.x, r0.x
    mad r0.x, r0.x, c14.z, c14.w
    sincos r1.y, r0.x
    mad o2.y, c11.x, r1.y, v1.y
    mad r0.y, c11.x, r1.y, v0.y
    mov r0.xz, v0
    mul r0.xyz, r0, c9.x
    mov r0.w, c15.x
    dp4 r1.x, c0, r0
    dp4 r1.y, c1, r0
    dp4 r1.z, c2, r0
    dp4 r1.w, c3, r0
    dp4 r2.x, c4, r1
    dp4 r2.y, c5, r1
    dp4 r2.z, c6, r1
    dp4 r2.w, c7, r1
    mad o0.xy, v2, c10, c10.zwzw
    mov o2.xz, v1
    mad o1.xy, r2.w, c255, r2
    mov o1.zw, r2

// approximately 32 instruction slots used


-- Fragment shader for "d3d9":
// Stats: 3 math
Vector4 _Color at 0

Shader Disassembly:
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 _Color;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   _Color       c0       1
//

    ps_3_0
    dcl_normal v0.xz
    mul r0.x, v0.z, v0.x
    abs_pp oC0.w, r0.x
    mov_pp oC0.xyz, c0

// approximately 3 instruction slots used


-- Vertex shader for "d3d11":
// Stats: 16 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "TexCoord"

Constant Buffer "$Globals" (112 bytes) on slot 0 {
  Float _Size at 48
  Vector4 _MainTex_ST at 64
  Float _Scale at 88
  Float _Speed at 92
  Float _Frequency at 96
}
Constant Buffer "UnityPerCamera" (144 bytes) on slot 1 {
  Vector4 _Time at 0
}
Constant Buffer "UnityPerDraw" (160 bytes) on slot 2 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 3 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz 
// NORMAL                   0   xyzw        1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// SV_POSITION              0   xyzw        1      POS   float   xyzw
// NORMAL                   0   xyz         2     NONE   float   xyz 
//
      vs_4_0
      dcl_constantbuffer CB0[7], immediateIndexed
      dcl_constantbuffer CB1[1], immediateIndexed
      dcl_constantbuffer CB2[4], immediateIndexed
      dcl_constantbuffer CB3[21], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_input v2.xy
      dcl_output o0.xy
      dcl_output_siv o1.xyzw, position
      dcl_output o2.xyz
      dcl_temps 2
   0: mad o0.xy, v2.xyxx, cb0[4].xyxx, cb0[4].zwzz
   1: add r0.x, v0.z, v0.x
   2: mul r0.y, cb0[5].w, cb1[0].w
   3: mad r0.x, r0.y, cb0[6].x, r0.x
   4: sincos r0.x, null, r0.x
   5: mad r1.y, cb0[5].z, r0.x, v0.y
   6: mad o2.y, cb0[5].z, r0.x, v1.y
   7: mov r1.xz, v0.xxzx
   8: mul r0.xyz, r1.xyzx, cb0[3].xxxx
   9: mul r1.xyzw, r0.yyyy, cb2[1].xyzw
  10: mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
  11: mad r0.xyzw, cb2[2].xyzw, r0.zzzz, r1.xyzw
  12: add r0.xyzw, r0.xyzw, cb2[3].xyzw
  13: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
  14: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
  15: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
  16: mad o1.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
  17: mov o2.xz, v1.xxzx
  18: ret 
// Approximately 0 instruction slots used


-- Fragment shader for "d3d11":
// Stats: 1 math, 1 temp registers
Constant Buffer "$Globals" (112 bytes) on slot 0 {
  Vector4 _Color at 32
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float       
// SV_POSITION              0   xyzw        1      POS   float       
// NORMAL                   0   xyz         2     NONE   float   x z 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[3], immediateIndexed
      dcl_input_ps linear v2.xz
      dcl_output o0.xyzw
      dcl_temps 1
   0: mul r0.x, v2.z, v2.x
   1: mov o0.w, |r0.x|
   2: mov o0.xyz, cb0[2].xyzx
   3: ret 
// Approximately 0 instruction slots used


 }
 UsePass "Legacy Shaders/VertexLit/SHADOWCASTER"
}
Fallback "Diffuse"
}